config/routes.rb
Bloobelly::Application.routes.draw do
  resources :shopping_trips do
    resources :food_items
  end

  

  match "oauth/callback" => "oauths#callback"
  
  match "about" => "page#about"
  match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  root :to => 'page#home'

end

app/models/shopping_trip.rb
class ShoppingTrip < ActiveRecord::Base
  belongs_to :user
  has_many :food_items
  accepts_nested_attributes_for :food_items
end

app/controllers/shopping_trips_controller.rb
class ShoppingTripsController < ApplicationController
  # GET /shopping_trips
  # GET /shopping_trips.json
  def index
    @shopping_trips = ShoppingTrip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shopping_trips }
    end
  end

  # GET /shopping_trips/1
  # GET /shopping_trips/1.json
  def show
    @shopping_trip = ShoppingTrip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shopping_trip }
    end
  end

  # GET /shopping_trips/new
  # GET /shopping_trips/new.json
  def new
    @shopping_trip = ShoppingTrip.new
    1.times do
      question = @shopping_trip.food_items.build
    end
    @food_names = {}
    @foods = []
    Food.all.each do |food|
      @food_names["#{food.name}"] = food.id
      @foods << food
    end
    

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shopping_trip }
    end
  end

  # GET /shopping_trips/1/edit
  def edit
    @shopping_trip = ShoppingTrip.find(params[:id])
  end

  # POST /shopping_trips
  # POST /shopping_trips.json
  def create
   # p = {"utf8"=>"✓", "authenticity_token"=>"jIcGQitXLtNukZjxCh11VITNOtZ09Xn5o31zRPMcuVw=",
   #    "shopping_trip"=>{"food_items_attributes"=>{"1319287074347"=>{"food"=>"rice - Small Bag", "number"=>"9"}}},
   #     "commit"=>"Create Shopping trip"}
   # 
   #@shopping_trip = ShoppingTrip.create()
   #@shopping_trip = ShoppingTrip.create()
   #@shopping_trip.food_items.create(params[:shopping_trip][:food_items_attributes])
    #params[:shopping_trip][:food_items_attributes].each do |item|
    #  @shopping_trip.food_items.create(:food_id => item[1], :number => item[2])
    #end
    
    @shopping_trip = ShoppingTrip.new({:user_id=>current_user.id},:total=>1230)
   
    respond_to do |format|
      if @shopping_trip.save
	totalusage=0
	params[:shopping_trip][:food_items_attributes].each do |item|
	  item=item[1]
	  FoodItem.create(:food_id => item['id'], :number => item['number'],:shopping_trip_id=>@shopping_trip.id)
	end
	total=0
	@shopping_trip.food_items.each do |fooditem|
	  total=total + fooditem.food.water_usage.to_i*fooditem.number.to_i
	end
	ShoppingTrip.update(@shopping_trip.id,:total=>total)
        format.html { redirect_to @shopping_trip, notice: 'Shopping trip was successfully created.' }
        format.json { render json: @shopping_trip, status: :created, location: @shopping_trip }
      else
        format.html { render action: "new" }
        format.json { render json: @shopping_trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shopping_trips/1
  # PUT /shopping_trips/1.json
  def update
    @shopping_trip = ShoppingTrip.find(params[:id])

    respond_to do |format|
      if @shopping_trip.update_attributes(params[:shopping_trip])
        format.html { redirect_to @shopping_trip, notice: 'Shopping trip was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @shopping_trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopping_trips/1
  # DELETE /shopping_trips/1.json
  def destroy
    @shopping_trip = ShoppingTrip.find(params[:id])
    @shopping_trip.destroy

    respond_to do |format|
      format.html { redirect_to shopping_trips_url }
      format.json { head :ok }
    end
  end
end

app/helpers/shopping_trips_helper.rb
module ShoppingTripsHelper
end

app/views/shopping_trips/_food_item_fields.html.erb
<div>

  	  <%= f.label :id, 'Food Name' %>
	  <br/>
	  <%= f.select :id, @food_names %> 
	  <%= f.label :number, ' Quantity --->' %>
	  <%= f.text_field :number %>
	
 


	
  <p><%# link_to_remove_fields 'remove', f %></p>
</div>

app/views/shopping_trips/_form.html.erb
<%= form_for(@shopping_trip) do |f| %>
  <% if @shopping_trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shopping_trip.errors.count, "error") %> prohibited this shopping_trip from being saved:</h2>

      <ul>
      <% @shopping_trip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div style="float:left; padding-left: 10px">
    <h2>Food Items</h2>
    <% f.fields_for :food_items do |builder| %>
        <%= render 'food_item_fields', :f => builder %>
    <% end %>

    <p><%= link_to_add_fields "Add Item", f, :food_items %></p>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shopping_trips/edit.html.erb
<h1>Editing shopping_trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @shopping_trip %> |
<%= link_to 'Back', shopping_trips_path %>

app/views/shopping_trips/index.html.erb
<h1>Listing shopping_trips</h1>

<table>
  <tr>
    <th>Integer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shopping_trips.each do |shopping_trip| %>
  <tr>
    <td><%= link_to 'Show', shopping_trip %></td>
    <td><%= link_to 'Edit', edit_shopping_trip_path(shopping_trip) %></td>
    <td><%= link_to 'Destroy', shopping_trip, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shopping trip', new_shopping_trip_path %>

app/views/shopping_trips/new.html.erb
<h1>New shopping_trip</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/shopping_trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>

</p>


<%= link_to 'Edit', edit_shopping_trip_path(@shopping_trip) %> |
<%= link_to 'Back', shopping_trips_path %>