config/routes.rb
Bloobelly::Application.routes.draw do
  resources :shopping_trips do
    resources :food_items
  end

  

  match "oauth/callback" => "oauths#callback"
  
  match "about" => "page#about"
  match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  root :to => 'page#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :authentications_attributes
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end
  validates_confirmation_of :password
  has_many :authentications, :dependent => :destroy
  has_many :shopping_trips
  accepts_nested_attributes_for :authentications
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end
  
  def show
    @user=User.find(params[:id])
    @shopping_trips=@user.shopping_trips
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shopping_trip }
    end
  
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_food_item.html.erb
<p class="fooditem"><%= food_item.food.name %> , 
<%= pluralize food_item.number,food_item.food.measure %> =
 <%= food_item.number.to_i   * food_item.food.water_usage.to_i   %> liters of water used</p>

app/views/users/_shopping_trip.html.erb
<h4 class="shoppingtrip">Water used this trip: <%=shopping_trip.total%></h4>
<%= render :partial => "food_item", :collection => shopping_trip.food_items %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>
or<br>
<%= link_to image_tag('fb.png',:alt => "Log in with Facebook"), auth_at_provider_path(:provider => :facebook),:rel=>"external" %>

app/views/users/show.html.erb
<h1>This users stats</h1>
<h2>Trips</h2>
<%= render :partial => "shopping_trip", :collection => @shopping_trips %>