config/routes.rb
Bloobelly::Application.routes.draw do
  resources :shopping_trips do
    resources :food_items
  end

  

  match "oauth/callback" => "oauths#callback"
  
  match "about" => "page#about"
  match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  root :to => 'page#home'

end

app/models/food_item.rb
class FoodItem < ActiveRecord::Base
  belongs_to :food
  belongs_to :shopping_trip
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @food_items }
    end
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
    @food_item = FoodItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @food_item }
    end
  end

  # GET /food_items/new
  # GET /food_items/new.json
  def new
    @food_item = FoodItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @food_item }
    end
  end

  # GET /food_items/1/edit
  def edit
    @food_item = FoodItem.find(params[:id])
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(params[:food_item])

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render json: @food_item, status: :created, location: @food_item }
      else
        format.html { render action: "new" }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /food_items/1
  # PUT /food_items/1.json
  def update
    @food_item = FoodItem.find(params[:id])

    respond_to do |format|
      if @food_item.update_attributes(params[:food_item])
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item = FoodItem.find(params[:id])
    @food_item.destroy

    respond_to do |format|
      format.html { redirect_to food_items_url }
      format.json { head :ok }
    end
  end
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/views/food_items/_food_item.html.erb
<p><%= food_item.food.name %> , <%= pluralize food_item.number,food_item.food.measure %> = <%= food_item.number * food_item.food.water_usage %></p>

app/views/food_items/_form.html.erb
<%= form_for(@food_item) do |f| %>
  <% if @food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% @food_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :measure %><br />
    <%= f.text_field :measure %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing food_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<h1>Listing food_items</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Water Usage</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @food_items.each do |food_item| %>
  <tr>
    <td><%= food_item.name %></td>
    <td><%= food_item.water_usage %></td>
    <td><%= link_to 'Show', food_item %></td>
    <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
    <td><%= link_to 'Destroy', food_item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Food item', new_food_item_path %>

app/views/food_items/new.html.erb
<h1>New food_item</h1>

<%= render 'form' %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Integer:</b>
  <%= @food_item.integer %>
</p>

<p>
  <b>Integer:</b>
  <%= @food_item.integer %>
</p>


<%= link_to 'Edit', edit_food_item_path(@food_item) %> |
<%= link_to 'Back', food_items_path %>