config/routes.rb
Bloobelly::Application.routes.draw do
  resources :shopping_trips do
    resources :food_items
  end

  

  match "oauth/callback" => "oauths#callback"
  
  match "about" => "page#about"
  match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  root :to => 'page#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloobelly</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div data-role = "page" data-theme = "b">
<div data-role = "header" data-theme = "b">  
<%= image_tag "Lizard.png", :height=>"28px", :alt=>"bloo belly",:class=>"ui-btn-left"%>
<h1>Bloo Belly</h2>
<p class="ui-btn-right">
<% if current_user %>
  Logged in as <%= link_to current_user.email, user_path(current_user) %>.
  <%= link_to "Log out", logout_path %>
<% else %>
  <%= link_to "Sign up", signup_path %> or
  <%= link_to "log in", login_path %>.
<% end %>
</p>
</div>
<%= yield %>
<div data-role = "footer" data-theme = "b" data-position="fixed">
<div data-role="navbar"><ul>
			<li><%= link_to "Go Shopping", new_shopping_trip_path , "data-icon"=>"plus"%></li>
			<li><%= link_to "Back", :back , "data-icon"=>"back"%></li>
			<li><%= link_to "Home", root_path , "data-icon"=>"home"%></li>
			<li><%= link_to "About Us", about_path , "data-icon"=>"info"%></li>
</ul></div>
        </div>
</div>
</body>
</html>